---
services:
  db:
    image: postgres:14.12-alpine3.20
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: chess
    networks:
      chessnet:
        ipv4_address: 10.1.0.2
    hostname: db.local
    healthcheck:
      test: "pg_isready"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  server:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: server.Dockerfile
    restart: always
      #    environment:
      #      PORT: "9090"
      #      DATABASE_URL: "postgres://admin:example@db.local:5432/chess"
    networks:
      chessnet:
        ipv4_address: 10.1.0.3
    hostname: l2chess.local
      #  client:
      #    build:
      #      context: ./
      #      dockerfile: client.Dockerfile
      #    ports:
      #      - "3000:3000"

networks:
  chessnet:
    name: chessnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1
